{% set name = "pegasus-wms.api" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pegasus_wms_api-{{ version }}.tar.gz
  sha256: 7303a4a5e294951da79441b6dab9fee4688563d60136c8a0132140b946b647c0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools <69
    - wheel
  run:
    - pegasus-wms.common
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - Pegasus.api
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show pegasus-wms.api

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
