{% set name = "pegasus-wms.api" %}
{% set version = "5.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f020354c24b548436644822b3fe8d8ff87fdf327ad729936520fda65560384a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - pegasus-wms.common
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - Pegasus.api
  commands:
    # check metadata
    - python -m pip check pegasus-wms.api
    - python -m pip show pegasus-wms.api

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
