schema_version: 1

context:
  name: pegasus-wms.api
  version: "5.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pegasus_wms_api-${{ version }}.tar.gz
  sha256: b6c4acd664bca6abdcbf05b2f82279c3357292a6d8e4d4cb2c2783772c81ec2b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - pegasus-wms.common >=5.1.0
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - Pegasus.api
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API
  homepage: https://pegasus.isi.edu
  repository: https://github.com/pegasus-isi/pegasus.git

extra:
  recipe-maintainers:
    - duncanmmacleod
    - mayani
    - rynge
